/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("vendors").del();
  await knex("vendors").insert([
    {
      id: 1,
      name: "Fresh Fields Organic",
      category: "Organic Produce",
      description: "Locally grown, organic fruits and vegetables.",
      contactInfo: "freshfields@gmail.com, (416) 555-1234",
      website: "https://freshfieldsorganic.ca",
      imageUrl: "https://example.com/freshfields.jpg",
      updates: "Now offering home delivery in Toronto!",
      location: "123 Greenway Ave, Toronto, ON",
      availability: "Monday - Saturday",
    },
    {
      id: 2,
      name: "Baker's Delight",
      category: "Baked Goods",
      description: "Handmade sourdough bread and pastries.",
      contactInfo: "bakersdelight@gmail.com, (647) 555-5678",
      website: "https://bakersdelight.ca",
      imageUrl: "https://example.com/bakersdelight.jpg",
      updates: "Try our new gluten-free bread!",
      location: "456 Pastry Lane, Toronto, ON",
      availability: "Wednesday - Sunday",
    },
    {
      id: 3,
      name: "Maple Honey Farms",
      category: "Honey & Maple Syrup",
      description: "Pure, locally sourced honey and maple syrup.",
      contactInfo: "maplehoneyfarms@gmail.com, (437) 555-7890",
      website: "https://maplehoneyfarms.ca",
      imageUrl: "https://example.com/maplehoney.jpg",
      updates: "Limited edition wildflower honey available!",
      location: "789 Honeycomb Dr, Mississauga, ON",
      availability: "Saturday - Sunday",
    },
    {
      id: 4,
      name: "Green Leaf Smoothies",
      category: "Beverages",
      description: "Freshly blended smoothies with organic ingredients.",
      contactInfo: "greenleaf@gmail.com, (905) 555-1111",
      website: "https://greenleafsmoothies.ca",
      imageUrl: "https://example.com/greenleaf.jpg",
      updates: "Get a free smoothie with every 5 purchases!",
      location: "321 Smoothie Blvd, Brampton, ON",
      availability: "Friday - Sunday",
    },
    {
      id: 5,
      name: "Toronto Cheese Co.",
      category: "Dairy & Cheese",
      description: "Aged, artisanal cheeses from Ontario farms.",
      contactInfo: "torontocheese@gmail.com, (416) 555-2222",
      website: "https://torontocheeseco.ca",
      imageUrl: "https://example.com/torontocheese.jpg",
      updates: "New truffle-infused cheddar now available!",
      location: "555 Dairy Rd, Scarborough, ON",
      availability: "Thursday - Saturday",
    },
    {
      id: 6,
      name: "Sunrise Microgreens",
      category: "Microgreens & Herbs",
      description: "Locally grown, nutrient-packed microgreens.",
      contactInfo: "sunrisegreens@gmail.com, (416) 555-3333",
      website: "https://sunrisemicrogreens.ca",
      imageUrl: "https://example.com/sunrisegreens.jpg",
      updates: "Now selling herb starter kits!",
      location: "78 Garden Lane, Toronto, ON",
      availability: "Monday - Friday",
    },
    {
      id: 7,
      name: "Farm to Cup Coffee Roasters",
      category: "Coffee & Tea",
      description: "Ethically sourced and locally roasted coffee beans.",
      contactInfo: "farmtocup@gmail.com, (647) 555-4444",
      website: "https://farmtocupcoffee.ca",
      imageUrl: "https://example.com/farmtocup.jpg",
      updates: "New Colombian roast available!",
      location: "901 Espresso Rd, Vaughan, ON",
      availability: "Tuesday - Sunday",
    },
    {
      id: 8,
      name: "The Vegan Butcher",
      category: "Plant-Based Foods",
      description: "Delicious plant-based meats and dairy alternatives.",
      contactInfo: "veganbutcher@gmail.com, (437) 555-5555",
      website: "https://theveganbutcher.ca",
      imageUrl: "https://example.com/veganbutcher.jpg",
      updates: "New smoked plant-based sausages!",
      location: "312 Tofu St, Markham, ON",
      availability: "Wednesday - Saturday",
    },
    {
      id: 9,
      name: "Wildberry Jams & Preserves",
      category: "Jams & Preserves",
      description: "Handmade, small-batch fruit preserves and jams.",
      contactInfo: "wildberryjams@gmail.com, (905) 555-6666",
      website: "https://wildberryjams.ca",
      imageUrl: "https://example.com/wildberryjams.jpg",
      updates: "Limited edition strawberry-basil jam available!",
      location: "29 Preserve Ln, Oakville, ON",
      availability: "Friday - Sunday",
    },
    {
      id: 10,
      name: "Golden Harvest Meats",
      category: "Grass-Fed Meats",
      description: "Ethically raised, grass-fed meats and poultry.",
      contactInfo: "goldenharvest@gmail.com, (905) 555-7777",
      website: "https://goldenharvestmeats.ca",
      imageUrl: "https://example.com/goldenharvest.jpg",
      updates: "Now offering organic, nitrate-free bacon!",
      location: "500 Farmstead Rd, Milton, ON",
      availability: "Thursday - Saturday",
    },
    {
      id: 11,
      name: "Bloomfield Flowers",
      category: "Flowers & Plants",
      description: "Beautiful fresh-cut flowers and potted plants.",
      contactInfo: "bloomfieldflowers@gmail.com, (416) 555-8888",
      website: "https://bloomfieldflowers.ca",
      imageUrl: "https://example.com/bloomfield.jpg",
      updates: "Spring tulips now in stock!",
      location: "601 Floral St, Toronto, ON",
      availability: "Monday - Saturday",
    },
    {
      id: 12,
      name: "The Nutty Baker",
      category: "Baked Goods",
      description: "Delicious nut-based cookies and pastries.",
      contactInfo: "nuttybaker@gmail.com, (647) 555-9999",
      website: "https://thenuttybaker.ca",
      imageUrl: "https://example.com/nuttybaker.jpg",
      updates: "Try our new hazelnut brownies!",
      location: "789 Almond Ave, Mississauga, ON",
      availability: "Wednesday - Sunday",
    },
  ]);
}
